name: Build APLAS-2020 version

on:
  push:
    paths-ignore:
      - README.md
    branches:
      - 'aplas2020-rework'
  #schedule:
  #  - cron: "0 13 * * 1"
    # https://jasonet.co/posts/scheduled-actions/

jobs:
  build:
    env:
      OPAMROOT: /home/user/.opam

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:pltlab
      options: --user user

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - run: opam install . --yes --deps-only --with-test #--with-doc

      - name: List installed packages
        run: opam list

      - run: opam exec -- dune build --profile=release
      - run: opam exec -- make test


