name: Build_master

on:
  push:
    paths-ignore:
      - 'papers/**'
      - '.github/workflows/FCPM.yml'
      # do not run CI if we are writing a paper
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
    branches:
      - 'master'

  schedule:
    - cron: "0 13 * * 1"
    # https://jasonet.co/posts/scheduled-actions/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        ocaml-version:
          - 4.10.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve date for cache key
        id: cache-key
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          # invalidate cache daily, gets built daily using a scheduled job
          key: ${{ steps.cache-key.outputs.date }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      #- run: opam pin add OCanren.dev . --no-action
      #- run: opam depext OCanren.dev --yes --with-test

      #- name: Install dependencies for documentation
      #  run: opam install odoc pa_ppx --yes

      - run: opam pin add . --no-action

      - run: opam pin add https://github.com/JetBrains-Research/GT.git --no-action
      
      - name: Installing depexts
        run: opam depext pat-match --yes --with-test

      - run: opam install GT-p5 --yes --verbose

      - name: Installing dependencies
        run: opam install . --deps-only --with-test --verbose
      - name: Building
        run: opam exec -- dune build switch/main_switch.exe --profile=release

      #- name: Build documentation
      #  run: opam exec -- dune build @doc

      #- name: Deploy documentation
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./_build/default/_doc/_html
